### ISSUE TITLE
Unhandled KeyNotFoundException for Key '20' in Dictionary in MSBP.cs

### ISSUE THREAD

**Issue by Digote** [KillzXGaming/MSBTConverter#2]
I'm testing a game, and I'm encountering a problem when compiling some files.

```C#
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '20' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CLMS.MSBP.TryGetTagConfigByControlTag(String aTagGroup, String aTagType) in C:\Users\Nathan\Documents\Forks\MSBTConverter\CLMS\Formats\MSBP.cs:line 435
   at CLMS.MSBT.FromYaml(String yaml, MSBP message_project) in C:\Users\Nathan\Documents\Forks\MSBTConverter\CLMS\Formats\MSBT.cs:line 437
   at MSBTConverter.Program.Main(String[] args) in C:\Users\Nathan\Documents\Forks\MSBTConverter\MSBTConverter\Program.cs:line 32
   
```

**Files used in the test, both .msbt and .msbp**

[Files.zip](https://github.com/user-attachments/files/15746334/Files.zip)

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/MSBTConverter/commit/df4b29e8ec496f2c469d21db30fd1a7b244a1847
